import { AuthError, requireRequestUser } from "@/lib/auth-store";
import { assertNotebookAccess } from "@/lib/notebook-store";
import { mutateWorkspace, readWorkspace, type Note } from "@/lib/workspace-store";

export async function GET(request: Request) { try { const user = await requireRequestUser(request); const { notebook } = await assertNotebookAccess(new URL(request.url).searchParams.get("notebookId"), user.id); return Response.json({ notes: (await readWorkspace(notebook.id)).notes }); } catch (error) { return fail(error); } }
export async function POST(request: Request) { try { const user = await requireRequestUser(request); const body = await request.json() as Partial<Note> & { notebookId?: string }; const { notebook } = await assertNotebookAccess(body.notebookId, user.id, "edit"); const now = new Date().toISOString(); const note: Note = { id: crypto.randomUUID(), title: String(body.title || "未命名笔记").slice(0, 120), content: String(body.content || "").slice(0, 100_000), citations: Array.isArray(body.citations) ? body.citations.slice(0, 100) : [], createdBy: user.id, createdAt: now, updatedAt: now }; await mutateWorkspace(notebook.id, (data) => ({ ...data, notes: [note, ...data.notes] })); return Response.json({ note }, { status: 201 }); } catch (error) { return fail(error); } }
export async function PATCH(request: Request) { try { const user = await requireRequestUser(request); const body = await request.json() as Partial<Note> & { notebookId?: string }; const { notebook } = await assertNotebookAccess(body.notebookId, user.id, "edit"); let note: Note | undefined; await mutateWorkspace(notebook.id, (data) => ({ ...data, notes: data.notes.map((item) => item.id === body.id ? (note = { ...item, title: String(body.title ?? item.title).slice(0, 120), content: String(body.content ?? item.content).slice(0, 100_000), updatedAt: new Date().toISOString() }) : item) })); if (!note) return Response.json({ error: "笔记不存在" }, { status: 404 }); return Response.json({ note }); } catch (error) { return fail(error); } }
export async function DELETE(request: Request) { try { const user = await requireRequestUser(request); const params = new URL(request.url).searchParams; const { notebook } = await assertNotebookAccess(params.get("notebookId"), user.id, "edit"); const id = params.get("id"); await mutateWorkspace(notebook.id, (data) => ({ ...data, notes: data.notes.filter((item) => item.id !== id) })); return Response.json({ ok: true }); } catch (error) { return fail(error); } }
function fail(error: unknown) { return Response.json({ error: error instanceof Error ? error.message : "请求失败" }, { status: error instanceof AuthError ? error.status : 400 }); }
