import { AuthError, requireRequestUser } from "@/lib/auth-store";
import { assertNotebookAccess } from "@/lib/notebook-store";
import { mutateWorkspace, readWorkspace, type Conversation, type ConversationMessage } from "@/lib/workspace-store";

export async function GET(request: Request) { try { const user = await requireRequestUser(request); const params = new URL(request.url).searchParams; const { notebook } = await assertNotebookAccess(params.get("notebookId"), user.id); const conversations = (await readWorkspace(notebook.id)).conversations; const id = params.get("id"); return Response.json(id ? { conversation: conversations.find((item) => item.id === id) || null } : { conversations: conversations.map(({ messages, ...item }) => ({ ...item, messageCount: messages.length, preview: messages.at(-1)?.text.slice(0, 120) || "" })) }); } catch (error) { return fail(error); } }
export async function POST(request: Request) { try { const user = await requireRequestUser(request); const body = await request.json() as { notebookId?: string; title?: string; selectedSourceIds?: string[] }; const { notebook } = await assertNotebookAccess(body.notebookId, user.id, "edit"); const now = new Date().toISOString(); const conversation: Conversation = { id: crypto.randomUUID(), title: String(body.title || "新对话").slice(0, 100), messages: [], selectedSourceIds: Array.isArray(body.selectedSourceIds) ? body.selectedSourceIds.slice(0, 100) : [], createdBy: user.id, createdAt: now, updatedAt: now }; await mutateWorkspace(notebook.id, (data) => ({ ...data, conversations: [conversation, ...data.conversations] })); return Response.json({ conversation }, { status: 201 }); } catch (error) { return fail(error); } }
export async function PATCH(request: Request) { try { const user = await requireRequestUser(request); const body = await request.json() as { notebookId?: string; id?: string; title?: string; selectedSourceIds?: string[]; appendMessages?: ConversationMessage[] }; const { notebook } = await assertNotebookAccess(body.notebookId, user.id, "edit"); let conversation: Conversation | undefined; await mutateWorkspace(notebook.id, (data) => ({ ...data, conversations: data.conversations.map((item) => item.id === body.id ? (conversation = { ...item, title: body.title ? body.title.slice(0, 100) : item.title, selectedSourceIds: Array.isArray(body.selectedSourceIds) ? body.selectedSourceIds.slice(0, 100) : item.selectedSourceIds, messages: Array.isArray(body.appendMessages) ? [...item.messages, ...body.appendMessages].slice(-200) : item.messages, updatedAt: new Date().toISOString() }) : item) })); if (!conversation) return Response.json({ error: "对话不存在" }, { status: 404 }); return Response.json({ conversation }); } catch (error) { return fail(error); } }
export async function DELETE(request: Request) { try { const user = await requireRequestUser(request); const params = new URL(request.url).searchParams; const { notebook } = await assertNotebookAccess(params.get("notebookId"), user.id, "edit"); const id = params.get("id"); await mutateWorkspace(notebook.id, (data) => ({ ...data, conversations: data.conversations.filter((item) => item.id !== id) })); return Response.json({ ok: true }); } catch (error) { return fail(error); } }
function fail(error: unknown) { return Response.json({ error: error instanceof Error ? error.message : "请求失败" }, { status: error instanceof AuthError ? error.status : 400 }); }
